#!/bin/bash
#SBATCH -J test
#SBATCH -A dtc-hwrf
#SBATCH --time=60
#SBATCH -p service
#SBATCH -n 1
#SBATCH -o test.out
#SBATCH -e test.err
#SBATCH -q windfall
#SBATCH --mail-user=Shaowu.Bao@noaa.gov
#SBATCH --mail-type="FAIL"
#SBATCH --mem=512M
#SBATCH -D../bin

cd  ..
#rm -fr bin
#mkdir bin
cd bin
source ~/.bashrc
source ../etc/Hera_setup_intel.sh
cd ../..
./ccpp/framework/scripts/ccpp_prebuild.py --config=./ccpp/config/ccpp_prebuild_config.py
cd scm/bin
cmake ../src
make
module load ncl
./run_gmtb_scm.py -c mycase
ncl var_out.ncl
mv psuadeApps_ct.out.* /home/Shaowu.Bao/nggps_hub/psuade
